feat: adjust grid for mobile
tum-ai/space pull request #231
Opened 2024-04-09 22:28 UTC by sofiiadan

Adjust space for mobile (not sure if this is all that is needed)

2024-04-15 17:27 UTC, Cyro292 commented
Looks Nice. 
Regarding Keys: 
There is a responsive layout issue observed when accessing the profile on devices with screens smaller than 500px in width. When the profile dropdown is activated, the size of the Table fluctuates, enlarging and shrinking dynamically. This behavior causes certain UI elements to be displaced, with some elements extending beyond the boundaries of the container.
 
<img width="347" alt="image" src="https://github.com/tum-ai/space/assets/78793822/07bb49e3-f9f9-4f60-8475-27261d4229db">

2024-04-15 18:00 UTC, Cyro292 commented
If you have time left a few minor things:

In opportunities when having a screen <440px. 
1. The gap between the frame and card increases excessively as the screen size decreases. The spacing should remain consistent regardless of screen size (red)
2. Additional spacing is needed between the Button and the Header to improve layout clarity (blue).



![image](https://github.com/tum-ai/space/assets/78793822/1d5c8882-9487-400f-b349-12996d3afcbe)

2024-06-21 09:42 UTC, BehsadRiemer requested changes
Overall, the changes are great and look good. Just some more fixes to make the UI more smooth. I will be commenting a summary.

2024-06-21 09:42 UTC, BehsadRiemer commented on app/layout.tsx
> +      <body className="">
this is a redundant change, can be taken out.

2024-06-21 09:42 UTC, BehsadRiemer commented on tailwind.config.ts
These are the default breakpoint widths, not needed.

2024-06-21 09:43 UTC, BehsadRiemer commented
<img width="509" alt="Screenshot 2024-06-21 at 11 22 41" src="https://github.com/tum-ai/space/assets/54889278/e6a6cb91-3e72-42ae-950e-e50a6dc2de15">
The delete button seems to overflow, maybe consider putting this under "Review a candidate"

2024-06-21 09:44 UTC, BehsadRiemer commented
<img width="572" alt="Screenshot 2024-06-21 at 11 22 10" src="https://github.com/tum-ai/space/assets/54889278/5411cc93-9956-4dda-bcf3-5b1ce9d380ce">

The questionnaire seems to be overflowing. Please consider making the size scale properly for mobile views.

2024-06-21 09:48 UTC, BehsadRiemer commented
<img width="548" alt="Screenshot 2024-06-21 at 11 45 12" src="https://github.com/tum-ai/space/assets/54889278/2cbd1437-0f0a-44e8-afc1-8fdb7b0d6d0c">

The save and delete button can also be placed below the "Configure an existing opportunity"

2024-06-21 09:49 UTC, BehsadRiemer commented
<img width="489" alt="Screenshot 2024-06-21 at 11 22 25" src="https://github.com/tum-ai/space/assets/54889278/f0c6613a-2d70-4e22-a13d-8ff7660a7bd8">

"Start new review" is overflowing here and can be placed below "see and edit your reviews" for mobile views.

2024-06-21 09:49 UTC, BehsadRiemer commented
<img width="511" alt="Screenshot 2024-06-21 at 11 21 52" src="https://github.com/tum-ai/space/assets/54889278/8eb73ed0-1e5a-46a4-84cb-ab5df1cb0e76">

The webhook URL can be bigger.

2024-06-21 09:50 UTC, BehsadRiemer commented
<img width="390" alt="Screenshot 2024-06-21 at 11 20 15" src="https://github.com/tum-ai/space/assets/54889278/0d3e8b75-9aeb-49c7-b48e-eab36094f6e2">

Export data can be placed below " applications for {opportunity name}"

2024-07-09 22:59 UTC, BehsadRiemer requested changes
LGTM, some minor changes that I added under comments.

2024-07-09 22:59 UTC, BehsadRiemer commented on app/opportunities/[opportunity_id]/applications/[application_id]/page.tsx
> +  const opportunityTitle = db.opportunity
I know you didn't write this but please make this a TRPC query

2024-07-09 22:59 UTC, BehsadRiemer commented on app/opportunities/[opportunity_id]/edit/editOpportunityForm.tsx
<img width="1607" alt="Screenshot 2024-07-10 at 00 46 44" src="https://github.com/tum-ai/space/assets/54889278/13bc6ead-4e20-4a83-b15b-307717835b81">

The description should be below for desktop views

2024-07-09 22:59 UTC, BehsadRiemer commented on components/header/index.tsx
> +            <Button asChild variant="outline" size="sm">
sign in styling is different here.

2024-08-10 20:42 UTC, BehsadRiemer requested changes
Looks great, but the description field in the creation and editing of an opportunity is still not consistent with the original design (please see pictures). 

<img width="1707" alt="Google Chrome 2024-08-10 22 37 58" src="https://github.com/user-attachments/assets/e8c86345-f2d5-4cdd-b1eb-37aed92cc1e9">

Please also make sure the padding of the titles is consistent:
<img width="320" alt="Google Chrome 2024-08-10 22 41 24" src="https://github.com/user-attachments/assets/0da8fd14-91ac-40b1-b046-ec7f27a7b03f">

2024-11-18 09:05 UTC, closed without merging